lib/groceries_list_web/router.ex
defmodule GroceriesListWeb.Router do
  use GroceriesListWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GroceriesListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GroceriesListWeb do
    pipe_through :browser

    get "/", GroceryController, :index
    resources "/groceries", GroceryController, only: [:index, :new, :create, :delete] do
      put "/add", GroceryController, :add
      put "/subtract", GroceryController, :subtract
      put "/complete", GroceryController, :complete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", GroceriesListWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GroceriesListWeb.Telemetry
    end
  end
end

lib/groceries_list/application.ex
defmodule GroceriesList.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      GroceriesList.Repo,
      # Start the Telemetry supervisor
      GroceriesListWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: GroceriesList.PubSub},
      # Start the Endpoint (http/https)
      GroceriesListWeb.Endpoint
      # Start a worker by calling: GroceriesList.Worker.start_link(arg)
      # {GroceriesList.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: GroceriesList.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    GroceriesListWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/groceries_list/grocery.ex
defmodule GroceriesList.Grocery do
  use Ecto.Schema
  import Ecto.Changeset

  schema "groceries" do
    field :name, :string
    field :quantity, :integer, default: 0
    field :complete, :boolean, default: false

    timestamps()
  end

  @doc false
  def changeset(grocery, attrs \\ %{}) do
    grocery
    |> cast(attrs, [:name, :quantity, :complete])
    |> validate_required([:name, :quantity])
    |> validate_length(:name, min: 3)
    |> validate_length(:name, max: 40)
    |> validate_number(:quantity, greater_than: 0)
  end
end

lib/groceries_list/repo.ex
defmodule GroceriesList.Repo do
  use Ecto.Repo,
    otp_app: :groceries_list,
    adapter: Ecto.Adapters.Postgres
end

lib/groceries_list_web/controllers/grocery_controller.ex
defmodule GroceriesListWeb.GroceryController do
  use GroceriesListWeb, :controller

  alias GroceriesList.{Grocery, Repo}
  require Ecto.Query

  def index(conn, _params) do
    groceries = Grocery |> Ecto.Query.order_by([asc: :complete, asc: :name] ) |> Repo.all()

    conn
    |> assign(:groceries, groceries)
    |> render(:index)
  end

  def new(conn, _params) do
    changeset = Grocery.changeset(%Grocery{})

    conn
    |> assign(:changeset, changeset)
    |> render(:new)
  end

  def create(conn, %{"grocery" => params}) do
    changeset = Grocery.changeset(%Grocery{}, params)

    case Repo.insert(changeset) do
      {:ok, grocery} ->
        conn
        |> put_flash(:info, "#{grocery.name} successfully added.")
        |> redirect(to: Routes.grocery_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "There was an error while creating the grocery.")
        |> render(:new, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    Repo.get!(Grocery, id) |> Repo.delete!

    conn
    |> put_flash(:info, "Grocery successfully deleted.")
    |> redirect(to: Routes.grocery_path(conn, :index))
  end

  def add(conn, %{"grocery_id" => id}) do
    grocery = Repo.get!(Grocery, id)

    grocery
    |> Grocery.changeset(%{quantity: grocery.quantity + 1})
    |> Repo.update()

    redirect(conn, to: Routes.grocery_path(conn, :index))
  end

  def subtract(conn, %{"grocery_id" => id}) do
    grocery = Repo.get!(Grocery, id)

    grocery
    |> Grocery.changeset(%{quantity: grocery.quantity - 1})
    |> Repo.update()

    redirect(conn, to: Routes.grocery_path(conn, :index))
  end

  def complete(conn, %{"grocery_id" => id}) do
    Repo.get!(Grocery, id) |> Grocery.changeset(%{complete: true}) |> Repo.update()

    IO.inspect(Repo.get!(Grocery, id))
    redirect(conn, to: Routes.grocery_path(conn, :index))
  end
end

lib/groceries_list_web/live/page_live.ex
defmodule GroceriesListWeb.PageLive do
  use GroceriesListWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not GroceriesListWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/groceries_list_web/views/error_view.ex
defmodule GroceriesListWeb.ErrorView do
  use GroceriesListWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/groceries_list_web/views/grocery_view.ex
defmodule GroceriesListWeb.GroceryView do
  use GroceriesListWeb, :view
end

lib/groceries_list_web/views/layout_view.ex
defmodule GroceriesListWeb.LayoutView do
  use GroceriesListWeb, :view
end

lib/groceries_list_web/live/page_live.html.leex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>

  <form phx-change="suggest" phx-submit="search">
    <input type="text" name="q" value="<%= @query %>" placeholder="Live dependency search" list="results" autocomplete="off"/>
    <datalist id="results">
      <%= for {app, _vsn} <- @results do %>
        <option value="<%= app %>"><%= app %></option>
      <% end %>
    </datalist>
    <button type="submit" phx-disable-with="Searching...">Go to Hexdocs</button>
  </form>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

lib/groceries_list_web/templates/grocery/index.html.eex
<div>
  <h2>Groceries to buy</h2>

  <ul>
  <%= for grocery <- @groceries do %>
    <li>
      <%= if grocery.complete do %>
        <s><%= grocery.quantity %> <%= grocery.name %></s>
      <% else %>
        <%= grocery.quantity %> <strong><%= grocery.name %></strong>
        <%= link(to: Routes.grocery_grocery_path(@conn, :add, grocery), method: :put) do %><i class="fas fa-plus-circle"></i><% end %>
        <%= link(to: Routes.grocery_grocery_path(@conn, :subtract, grocery), method: :put) do %><i class="fas fa-minus-circle"></i><% end %>
        <%= link(to: Routes.grocery_grocery_path(@conn, :complete, grocery), method: :put) do %><i class="fas fa-check"></i><% end %>
        <%= link(to: Routes.grocery_path(@conn, :delete, grocery), method: :delete) do %><i class="far fa-trash-alt"></i><% end %>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

<%= link("Add a new grocery", to: Routes.grocery_path(@conn, :new)) %>

lib/groceries_list_web/templates/grocery/new.html.eex
<h2>Add a new grocery</h2>

<%= form_for @changeset, Routes.grocery_path(@conn, :create), fn f -> %>
  <%= label f, :name, "Name" %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :quantity, "Quantity" %>
  <%= number_input f, :quantity %>
  <%= error_tag f, :quantity %>

  <%= submit "Add" %>
<% end %>

lib/groceries_list_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/groceries_list_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/groceries_list_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "GroceriesList", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>